# Generated by Django 5.1.7 on 2025-03-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_review_movie_review_stars_alter_review_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Director',
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_app.director'),
            preserve_default=False,
        ),
    ]
